name: wffrasah
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+4

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  intl: any
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0

  # Supabase
  supabase_flutter: ^2.10.1

  # UI & Animations
  lottie: ^3.3.2
  flutter_svg: ^2.2.3
  carousel_slider: ^5.1.1
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^2.0.1
  google_fonts: ^8.0.0
  custom_navigation_bar: ^0.8.2
  quickalert: ^1.1.0

  # State Management & Storage
  provider: ^6.1.2
  shared_preferences: ^2.5.3

  # Utilities
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  http: ^1.3.0
  image_picker: ^1.2.0
  googleapis_auth: ^2.0.0
  random_string: ^2.3.1
  package_info_plus: ^8.1.2
  permission_handler: ^12.0.1
  app_settings: ^6.0.0

  # âœ… FIX: needed by import in web_coupon_card.dart
  vector_math: ^2.1.4

  # Firebase
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.3

flutter_native_splash:
  color: "#ffffff"
  android_12:
    color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/animations/coupon_animation.json
    - assets/image/
    - assets/icon/
    - assets/lang/ar.json
    - assets/lang/en.json
    

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
