name: rbhan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8

  # Supabase
  supabase_flutter: ^2.5.6

  # UI & Animations
  lottie: ^3.3.1
  flutter_svg: ^2.0.17
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.0+3
  google_fonts: ^6.2.1
  custom_navigation_bar: ^0.8.2
  quickalert: ^1.1.0
  flutter_launcher_icons: ^0.14.4

  # State Management & Storage
  provider: ^6.1.2
  shared_preferences: ^2.5.2

  # Utilities
  clipboard: ^0.1.3
  share_plus: ^12.0.1
  url_launcher: ^6.3.1
  http: ^1.3.0
  image_picker: ^1.2.0
  googleapis_auth: ^1.6.0
  random_string: ^2.3.1
  package_info_plus: ^8.0.0
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  permission_handler: ^12.0.1
  app_settings: ^6.0.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# إعدادات flutter_native_splash
#
flutter_native_splash:
  color: "#ffffff" # لون خلفية شاشة البداية (الأبيض ليطابق صفحة الـ Lottie)
  android_12:
    color: "#ffffff"
  # ملاحظة: لم نضف صورة هنا لأننا سننتقل فوراً لصفحة الأنيميشن الخاصة بك

flutter:
  uses-material-design: true

  assets:
    - assets/animations/coupon_animation.json

    - assets/image/
    - assets/icon/
    - assets/lang/ar.json
    - assets/lang/en.json

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700